// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using KenticoCloud.ContentManagement.Models.Items;
using KenticoCloud.ContentManagement.Models.Assets;

namespace KenticoCloudImport
{
    public partial class SimplePage
    {
        [JsonProperty("page_teaser")]
        public IEnumerable<AssetIdentifier> PageTeaser { get; set; }
        [JsonProperty("page_title")]
        public string PageTitle { get; set; }
        [JsonProperty("page_content")]
        public string PageContent { get; set; }
        [JsonProperty("dish_colour")]
        public IEnumerable<TaxonomyTermIdentifier> DishColour { get; set; }
    }
}